### ISSUE TITLE
Fail to build because of "Failed to run custom build command for '[random packages differ every time]'"

### ISSUE THREAD

**Issue by loeeeee** [SichangHe/scraper#1]
I tried to build the scraper. However, after the rustup installed according to the rust site, I still cannot build the scraper. 

The code

    $ cargo build --release --verbose
           Compiling proc-macro2 v1.0.47
           Fresh unicode-ident v1.0.5
           Fresh autocfg v1.1.0
           Fresh cfg-if v1.0.0
           Fresh once_cell v1.15.0
           Fresh scopeguard v1.1.0
           Fresh ppv-lite86 v0.2.16
           Fresh smallvec v1.10.0
           Fresh pkg-config v0.3.25
           Fresh cc v1.0.73
           Fresh pin-project-lite v0.2.9
           Fresh bytes v1.2.1
           Fresh siphasher v0.3.10
           Fresh version_check v0.9.4
           Fresh new_debug_unreachable v1.0.4
           Fresh itoa v1.0.4
           Fresh mac v0.1.1
           Fresh fnv v1.0.7
           Fresh bitflags v1.3.2
           Fresh foreign-types-shared v0.1.1
           Fresh utf-8 v0.7.6
           Fresh precomputed-hash v0.1.1
           Fresh pin-utils v0.1.0
           Fresh hashbrown v0.12.3
           Fresh futures-sink v0.3.25
           Fresh tinyvec_macros v0.1.0
           Fresh try-lock v0.2.3
           Fresh openssl-probe v0.1.5
           Fresh percent-encoding v2.2.0
           Fresh httpdate v1.0.2
           Fresh tower-service v0.3.2
           Fresh unicode-bidi v0.3.8
         Running `/blahblahblah/target/release/build/proc-macro2-43ef730515044743/build-script-build`
    error: failed to run custom build command for `proc-macro2 v1.0.47`
    
    Caused by:
      could not execute process `/blahblahblah/target/release/build/proc-macro2-43ef730515044743/build-script-build` (never executed)
    
    Caused by:
      Invalid argument (os error 22)
    warning: build failed, waiting for other jobs to finish...

However, I could install the scraper from cargo. 
The code:

    $ cargo install recursive_scraper
        Updating `mirror` index
      Installing recursive_scraper v0.5.1
       Compiling proc-macro2 v1.0.47
       Compiling quote v1.0.21
       Compiling unicode-ident v1.0.5
       Compiling autocfg v1.1.0
       Compiling libc v0.2.137
       Compiling syn v1.0.105
       Compiling cfg-if v1.0.0
       Compiling log v0.4.17
       Compiling once_cell v1.16.0
       Compiling parking_lot_core v0.9.5
       Compiling scopeguard v1.1.0
       Compiling smallvec v1.10.0
       Compiling ppv-lite86 v0.2.17
       Compiling getrandom v0.1.16
       Compiling siphasher v0.3.10
       Compiling memchr v2.5.0
       Compiling serde_derive v1.0.148
       Compiling serde v1.0.148
       Compiling cc v1.0.77
       Compiling pkg-config v0.3.26
       Compiling pin-project-lite v0.2.9
       Compiling futures-core v0.3.25
       Compiling bytes v1.3.0
       Compiling new_debug_unreachable v1.0.4
       Compiling version_check v0.9.4
       Compiling bitflags v1.3.2
       Compiling mac v0.1.1
       Compiling futures-task v0.3.25
       Compiling itoa v1.0.4
       Compiling fnv v1.0.7
       Compiling foreign-types-shared v0.1.1
       Compiling openssl v0.10.43
       Compiling utf-8 v0.7.6
       Compiling precomputed-hash v0.1.1
       Compiling futures-util v0.3.25
       Compiling pin-utils v0.1.0
       Compiling futures-channel v0.3.25
       Compiling hashbrown v0.12.3
       Compiling httparse v1.8.0
       Compiling native-tls v0.2.11
       Compiling io-lifetimes v1.0.3
       Compiling tinyvec_macros v0.1.0
       Compiling futures-sink v0.3.25
       Compiling openssl-probe v0.1.5
       Compiling try-lock v0.2.3
       Compiling percent-encoding v2.2.0
       Compiling rustix v0.36.4
       Compiling linux-raw-sys v0.1.3
       Compiling encoding_rs v0.8.31
       Compiling tower-service v0.3.2
       Compiling httpdate v1.0.2
       Compiling unicode-bidi v0.3.8
       Compiling heck v0.4.0
       Compiling ryu v1.0.11
       Compiling futf v0.1.5
       Compiling foreign-types v0.3.2
       Compiling tinyvec v1.6.0
       Compiling anyhow v1.0.66
       Compiling bit-vec v0.6.3
       Compiling regex-syntax v0.6.28
       Compiling termcolor v1.1.3
       Compiling os_str_bytes v6.4.1
       Compiling strsim v0.10.0
       Compiling mime v0.3.16
       Compiling base64 v0.13.1
       Compiling form_urlencoded v1.1.0
       Compiling humantime v2.1.0
       Compiling phf_shared v0.10.0
       Compiling phf_shared v0.8.0
       Compiling tracing-core v0.1.30
       Compiling tendril v0.4.3
       Compiling ipnet v2.5.1
       Compiling bit-set v0.5.3
       Compiling proc-macro-error-attr v1.0.4
       Compiling proc-macro-error v1.0.4
       Compiling clap_lex v0.3.0
       Compiling lock_api v0.4.9
       Compiling tokio v1.22.0
       Compiling indexmap v1.9.2
       Compiling slab v0.4.7
       Compiling phf v0.8.0
       Compiling http v0.2.8
       Compiling want v0.3.0
       Compiling tracing v0.1.37
       Compiling openssl-sys v0.9.78
       Compiling aho-corasick v0.7.20
       Compiling unicode-normalization v0.1.22
       Compiling getrandom v0.2.8
       Compiling http-body v0.4.5
       Compiling rand_core v0.5.1
       Compiling rand_core v0.6.4
       Compiling rand_pcg v0.2.1
       Compiling rand_chacha v0.2.2
       Compiling rand_chacha v0.3.1
       Compiling idna v0.3.0
       Compiling rand v0.7.3
       Compiling rand v0.8.5
       Compiling mio v0.8.5
       Compiling num_cpus v1.14.0
       Compiling socket2 v0.4.7
       Compiling time v0.1.45
       Compiling atty v0.2.14
       Compiling url v2.3.1
       Compiling regex v1.7.0
       Compiling parking_lot v0.12.1
       Compiling phf_generator v0.8.0
       Compiling phf_generator v0.10.0
       Compiling phf_codegen v0.8.0
       Compiling string_cache_codegen v0.5.2
       Compiling markup5ever v0.10.1
       Compiling env_logger v0.9.3
       Compiling is-terminal v0.4.1
       Compiling tokio-macros v1.8.2
       Compiling openssl-macros v0.1.0
       Compiling html5ever v0.25.2
       Compiling clap_derive v4.0.21
       Compiling clap v4.0.29
       Compiling tokio-util v0.7.4
       Compiling tokio-native-tls v0.3.0
       Compiling h2 v0.3.15
       Compiling string_cache v0.8.4
       Compiling serde_urlencoded v0.7.1
       Compiling toml v0.5.9
       Compiling xml5ever v0.16.2
       Compiling markup5ever_rcdom v0.1.0
       Compiling hyper v0.14.23
       Compiling select v0.5.0
       Compiling hyper-tls v0.5.0
       Compiling reqwest v0.11.13
       Compiling recursive_scraper v0.5.1
        Finished release [optimized] target(s) in 1m 22s
      Installing /home/loe/.cargo/bin/recursive_scraper

I am currently running Ubuntu 22.04 TLS with latest packages on an x86_64 processor with sufficient RAM and proper Internet connection. But I changed the source to the SJTU mirror site, which in theory should not cause problem.

Also, I tried building on other machines. It works fine. But it does not work on my machine.  What should I do to provide more information?

**Comment by SichangHe** [comment]
What is your `rustc` version? How did you install it?
It looks to me that your `cargo` is broken. Could you update `cargo` and `rustc` or reinstall them?

Steven Hé (Sīchàng)

**Comment by loeeeee** [comment]
I figured out the root problem. First, I checked the version of the rustc and cargo. They are the latest. Then, I realized that it was my fault, because I was using trying build the scraper on a SMB mount. As SMB is not a block storage, some wired behavior happens probably because of the permission issues. I copied the code into the local storage, and it worked fine.
Thanks anyway! :)
